server:
  # 应用服务 WEB 访问端口
  port: 8090
spring:
  profiles:
    active: dev
  application:
    # 应用名称
    name: goods
  cloud:
    nacos:
      discovery:
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: publicRedisConfig
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 172.16.104.70:8848
        # Nacos认证信息
        username: nacos
        password: nacos
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
      web-stat-filter:
        enabled: true
      # 数据库驱动：
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据源名称
      name: defaultDataSource
      # 数据库连接地址
      url: jdbc:mysql://localhost:3306/liuyd_db?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&useSSL=false
      # 数据库用户名&密码：
      username: 'root'
      password: 'root'
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 20
      min-idle: 20
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      pool-prepared-statements: true
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  #redis 配置
  redis:
    database: 7
    host: 172.16.100.82
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 'redis@7302.com'
    port: 7302
knife4j:
  basic:
    enable: true
    username: zzdz
    password: zzdz
mybatis-plus:
  mapper-locations: classpath*:com/lyd/goods/dao/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: id_worker
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
feign:
  httpclient:
    enabled: true